// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc4DgoyoSTXbXqOrcYpu_PhONlpe2JMPU',
    appId: '1:957830471194:web:f7f97200dfa4ecf3887ba3',
    messagingSenderId: '957830471194',
    projectId: 'youbettersandbox',
    authDomain: 'youbettersandbox.firebaseapp.com',
    storageBucket: 'youbettersandbox.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb2iG6Z4e0GcORKii7YGzHvQo9FSUDdeQ',
    appId: '1:957830471194:android:791716cf60a7d987887ba3',
    messagingSenderId: '957830471194',
    projectId: 'youbettersandbox',
    storageBucket: 'youbettersandbox.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjPvj109wKo6mtNu3rCOt3dG1V7QixPY8',
    appId: '1:957830471194:ios:4362cb3d5b5a53b1887ba3',
    messagingSenderId: '957830471194',
    projectId: 'youbettersandbox',
    storageBucket: 'youbettersandbox.appspot.com',
    iosBundleId: 'com.example.youBetter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjPvj109wKo6mtNu3rCOt3dG1V7QixPY8',
    appId: '1:957830471194:ios:4362cb3d5b5a53b1887ba3',
    messagingSenderId: '957830471194',
    projectId: 'youbettersandbox',
    storageBucket: 'youbettersandbox.appspot.com',
    iosBundleId: 'com.example.youBetter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc4DgoyoSTXbXqOrcYpu_PhONlpe2JMPU',
    appId: '1:957830471194:web:70b894e34846d184887ba3',
    messagingSenderId: '957830471194',
    projectId: 'youbettersandbox',
    authDomain: 'youbettersandbox.firebaseapp.com',
    storageBucket: 'youbettersandbox.appspot.com',
  );

}